[package]
name = "heic-to-gxml"
version = "0.1.0"
authors = ["Johannes Wünsche <johannes@spacesnek.rocks>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libheif-rs = { git = "https://github.com/spraints/libheif-rs.git" }
png = "0.16.8"
